### ISSUE TITLE
NIH_Building Sustainable Software Tools for Open Science (R03 Clinical Trial Not Allowed), Request for Application, Due: Dec 04, 2024

### ISSUE THREAD

**Issue by opencode4good** [numfocus/project-fundraising#20]
**Building Sustainable Software Tools for Open Science (R03 Clinical Trial Not Allowed), Request for Application**
* Date Posted:  Nov 04, 2024
* **Deadline:  Dec 04, 2024**
* **Funding Institution(s):**  National Institutes of Health, Office of Data Science Strategy (ODSS); National Eye Institute (NEI); National Heart, Lung, and Blood Institute (NHLBI); National Human Genome Research Institute (NHGRI); National Institute on Aging (NIA); National Institute on Alcohol Abuse and Alcoholism (NIAAA); National Institute of Arthritis and Musculoskeletal and Skin Diseases (NIAMS); National Institute of Biomedical Imaging and Bioengineering (NIBIB); Eunice Kennedy Shriver National Institute of Child Health and Human Development (NICHD); National Institute on Deafness and Other Communication Disorders (NIDCD); National Institute of Dental and Craniofacial Research (NIDCR); National Institute of Diabetes and Digestive and Kidney Diseases (NIDDK); National Institute on Drug Abuse (NIDA); National Institute of Environmental Health Sciences (NIEHS); National Institute of Mental Health (NIMH); National Institute of Neurological Disorders and Stroke (NINDS); National Institute on Minority Health and Health Disparities (NIMHD); National Library of Medicine (NLM); National Center for Complementary and Integrative Health (NCCIH); National Cancer Institute (NCI);
  * **Brief Description:** The purpose of this notice of funding opportunity (NOFO) is to enhance the sustainability and impact of research software tools by enabling the use of best practices and design principles in software development and by leveraging continuing advances in computing. It is also expected to facilitate the creation of vibrant partnerships between developers and users of software and tools, and to promote FAIR practices for research software to maximize research value.
* **Link:** https://www.niddk.nih.gov/research-funding/current-opportunities/rfa-od-24-010

**Comment by rcurtin** [comment]
mlpack will apply to the upcoming June deadline for this grant.
